package com.cts.fms.pojo;
// Generated Oct 31, 2019 7:35:33 PM by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name="employee"
    ,catalog="fsd"
)
public class Employee  implements java.io.Serializable {


     private Integer idEmployee;
     private String firstName;
     private String lastName;
     private String phone;
     private String email;
     private String password;
     private String baseLocation;
     private String type;

	
	 private Set<EventDetails> eventDetailses = new HashSet<EventDetails>(0);
	 /* * private Set<EventEnrollment> eventEnrollments = new
	 * HashSet<EventEnrollment>(0);
	 */
    public Employee() {
    }

    public Employee(String firstName, String lastName, String phone, String email, String password, String baseLocation, String type, Set<EventDetails> eventDetailses) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.phone = phone;
       this.email = email;
       this.password = password;
       this.baseLocation = baseLocation;
       this.type = type;
		
         this.eventDetailses = eventDetailses; 
         /*	    this.eventEnrollments =eventEnrollments;
		 */
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_employee", unique=true, nullable=false)
    public Integer getIdEmployee() {
        return this.idEmployee;
    }
    
    public void setIdEmployee(Integer idEmployee) {
        this.idEmployee = idEmployee;
    }

    
    @Column(name="first_name", length=45)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="last_name", length=45)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="phone")
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="email", length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="password", length=45)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="base_location", length=45)
    public String getBaseLocation() {
        return this.baseLocation;
    }
    
    public void setBaseLocation(String baseLocation) {
        this.baseLocation = baseLocation;
    }

    
    @Column(name="type", length=45)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

	
	
	  @OneToMany(fetch=FetchType.LAZY, mappedBy="idEmployee") public
	  Set<EventDetails> getEventDetailses() { return this.eventDetailses; }
	  
	  public void setEventDetailses(Set<EventDetails> eventDetailses) {
	  this.eventDetailses = eventDetailses; }
	 
	  
	/*
	 * @OneToMany(fetch=FetchType.LAZY, mappedBy="employee") public
	 * Set<EventEnrollment> getEventEnrollments() { return this.eventEnrollments; }
	 * 
	 * public void setEventEnrollments(Set<EventEnrollment> eventEnrollments) {
	 * this.eventEnrollments = eventEnrollments; }
	 */




}


