package com.cts.fms.pojo;
// Generated Oct 31, 2019 7:35:33 PM by Hibernate Tools 3.4.0.CR1


import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EventDetails generated by hbm2java
 */
@Entity
@Table(name="event_details"
    ,catalog="fsd"
)
public class EventDetails  implements java.io.Serializable {


     private Integer idEventDetails;
     private Integer idEmployee;
	 private String month;
     private String beneficiaryName;
     private String venueAddress;
     private String councilName;
     private String projectCategory;
     private String name;
     private String description;
     private String eventID;
     
     
     @Column(name="event_id")
     public String getEventID() {
		return eventID;
	}

	public void setEventID(String eventID) {
		this.eventID = eventID;
	}

	private Date date;
     private Integer totalVolunteers;
     private Integer totalVolunteersHours;
     private Integer totalTravel;
     private String overallVolunteering;
     private Integer livesImpacted;
     private String activityType;
     private String status;
    // private Set<EventEnrollment> eventEnrollments = new HashSet<EventEnrollment>(0);

    public EventDetails() {
    }

    public EventDetails(String month, String beneficiaryName, String venueAddress, String councilName, String projectCategory, String name, String description, Date date, Integer totalVolunteers, Integer totalVolunteersHours, Integer totalTravel, String overallVolunteering, Integer livesImpacted, String activityType, String status,String eventID) {
    //   this.employee = employee;
       this.month = month;
       this.beneficiaryName = beneficiaryName;
       this.venueAddress = venueAddress;
       this.councilName = councilName;
       this.projectCategory = projectCategory;
       this.name = name;
       this.description = description;
       this.date = date;
       this.totalVolunteers = totalVolunteers;
       this.totalVolunteersHours = totalVolunteersHours;
       this.totalTravel = totalTravel;
       this.overallVolunteering = overallVolunteering;
       this.livesImpacted = livesImpacted;
       this.activityType = activityType;
       this.status = status;
       this.eventID = eventID;
       //this.eventEnrollments = eventEnrollments;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_event_details", unique=true, nullable=false)
    public Integer getIdEventDetails() {
        return this.idEventDetails;
    }
    
    public void setIdEventDetails(Integer idEventDetails) {
        this.idEventDetails = idEventDetails;
    }

    @Column(name="id_employee")
    public Integer getIdEmployee() {
		return idEmployee;
	}

	public void setIdEmployee(Integer idEmployee) {
		this.idEmployee = idEmployee;
	}
	/*
	 * @ManyToOne(fetch=FetchType.LAZY)
	 * 
	 * @JoinColumn(name="id_employee") public Employee getEmployee() { return
	 * this.employee; }
	 * 
	 * public void setEmployee(Employee employee) { this.employee = employee; }
	 */

    
    @Column(name="month", length=45)
    public String getMonth() {
        return this.month;
    }
    
    public void setMonth(String month) {
        this.month = month;
    }

    
    @Column(name="beneficiary_name", length=45)
    public String getBeneficiaryName() {
        return this.beneficiaryName;
    }
    
    public void setBeneficiaryName(String beneficiaryName) {
        this.beneficiaryName = beneficiaryName;
    }

    
    @Column(name="venue_address", length=45)
    public String getVenueAddress() {
        return this.venueAddress;
    }
    
    public void setVenueAddress(String venueAddress) {
        this.venueAddress = venueAddress;
    }

    
    @Column(name="council_name", length=45)
    public String getCouncilName() {
        return this.councilName;
    }
    
    public void setCouncilName(String councilName) {
        this.councilName = councilName;
    }

    
    @Column(name="project_category", length=45)
    public String getProjectCategory() {
        return this.projectCategory;
    }
    
    public void setProjectCategory(String projectCategory) {
        this.projectCategory = projectCategory;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="description", length=45)
    public String getDescription() {
        return this.description;
    }
    
   
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date", length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="total_volunteers")
    public Integer getTotalVolunteers() {
        return this.totalVolunteers;
    }
    
    public void setTotalVolunteers(Integer totalVolunteers) {
        this.totalVolunteers = totalVolunteers;
    }

    
    @Column(name="total_volunteers_hours")
    public Integer getTotalVolunteersHours() {
        return this.totalVolunteersHours;
    }
    
    public void setTotalVolunteersHours(Integer totalVolunteersHours) {
        this.totalVolunteersHours = totalVolunteersHours;
    }

    
    @Column(name="total_travel")
    public Integer getTotalTravel() {
        return this.totalTravel;
    }
    
    public void setTotalTravel(Integer totalTravel) {
        this.totalTravel = totalTravel;
    }

    
    @Column(name="overall_volunteering", length=45)
    public String getOverallVolunteering() {
        return this.overallVolunteering;
    }
    
    public void setOverallVolunteering(String overallVolunteering) {
        this.overallVolunteering = overallVolunteering;
    }

    
    @Column(name="lives_impacted")
    public Integer getLivesImpacted() {
        return this.livesImpacted;
    }
    
    public void setLivesImpacted(Integer livesImpacted) {
        this.livesImpacted = livesImpacted;
    }

    
    @Column(name="activity_type", length=45)
    public String getActivityType() {
        return this.activityType;
    }
    
    public void setActivityType(String activityType) {
        this.activityType = activityType;
    }

    
    @Column(name="status", length=45)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

	/*
	 * @OneToMany(fetch=FetchType.LAZY, mappedBy="eventDetails") public
	 * Set<EventEnrollment> getEventEnrollments() { return this.eventEnrollments; }
	 * 
	 * public void setEventEnrollments(Set<EventEnrollment> eventEnrollments) {
	 * this.eventEnrollments = eventEnrollments; }
	 */




}


