package com.cts.fms.pojo;
// Generated Oct 31, 2019 7:35:33 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EventEnrollment generated by hbm2java
 */
@Entity
@Table(name="event_enrollment"
    ,catalog="fsd"
)
public class EventEnrollment  implements java.io.Serializable {


     private Integer idEventEnrollment;
     private EventDetails eventDetails;
     private Employee employee;
     private Integer volunteerHours;
     private Integer travelHours;
     private String businessUnit;
     private String iiepCategory;
     private String enrollmentStatus;

    public EventEnrollment() {
    }

    public EventEnrollment(EventDetails eventDetails, Employee employee, Integer volunteerHours, Integer travelHours, String businessUnit, String iiepCategory, String enrollmentStatus) {
       this.eventDetails = eventDetails;
       this.employee = employee;
       this.volunteerHours = volunteerHours;
       this.travelHours = travelHours;
       this.businessUnit = businessUnit;
       this.iiepCategory = iiepCategory;
       this.enrollmentStatus = enrollmentStatus;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_event_enrollment", unique=true, nullable=false)
    public Integer getIdEventEnrollment() {
        return this.idEventEnrollment;
    }
    
    public void setIdEventEnrollment(Integer idEventEnrollment) {
        this.idEventEnrollment = idEventEnrollment;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_event")
    public EventDetails getEventDetails() {
        return this.eventDetails;
    }
    
    public void setEventDetails(EventDetails eventDetails) {
        this.eventDetails = eventDetails;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_employee")
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    
    @Column(name="volunteer_hours")
    public Integer getVolunteerHours() {
        return this.volunteerHours;
    }
    
    public void setVolunteerHours(Integer volunteerHours) {
        this.volunteerHours = volunteerHours;
    }

    
    @Column(name="travel_hours")
    public Integer getTravelHours() {
        return this.travelHours;
    }
    
    public void setTravelHours(Integer travelHours) {
        this.travelHours = travelHours;
    }

    
    @Column(name="business_unit", length=45)
    public String getBusinessUnit() {
        return this.businessUnit;
    }
    
    public void setBusinessUnit(String businessUnit) {
        this.businessUnit = businessUnit;
    }

    
    @Column(name="iiep_category", length=45)
    public String getIiepCategory() {
        return this.iiepCategory;
    }
    
    public void setIiepCategory(String iiepCategory) {
        this.iiepCategory = iiepCategory;
    }

    
    @Column(name="enrollment_status", length=45)
    public String getEnrollmentStatus() {
        return this.enrollmentStatus;
    }
    
    public void setEnrollmentStatus(String enrollmentStatus) {
        this.enrollmentStatus = enrollmentStatus;
    }




}


